### ISSUE TITLE
Some error  about Mercator projection in the demo.

### ISSUE THREAD

**Issue by 958117216** [tu-darmstadt-ros-pkg/image_projection#10]
I run the demo follow the instruct, I got 
![2023-08-02 17-37-33 的屏幕截图](https://github.com/tu-darmstadt-ros-pkg/image_projection/assets/46185326/e8c8e9e9-3571-4586-8f63-f19ccabe08be)
![2023-08-02 17-38-49 的屏幕截图](https://github.com/tu-darmstadt-ros-pkg/image_projection/assets/46185326/de658e5b-d909-4fc3-81de-2e7b5ec349cd)

The error in the above picture is only the problem with rqt, not the cause of the mercator projection error.
My system is Ubuntu18.04,ROS is Melodic.How to solve the problem?

**Comment by Martin-Oehler** [comment]
Hey,
thanks for trying out the demo and pointing out this error. I recently changed the way the parameters are interpreted for the mercator projection because previously, non-square pixels were possible. Apparently, the FOV of the demo config exceeded 360°, resulting in a weird projection.

I updated the demo config. Please update and try again.

Best regards,
Martin

**Comment by 958117216** [comment]
After modifying the parameters, the demo works fine. 

Thank you so much for your generous answer!!!
