### ISSUE TITLE
Correct parameters for mercator projection

### ISSUE THREAD

**Issue by Adidushi** [tu-darmstadt-ros-pkg/image_projection#2]
I've been trying to get this package working with 4 pinhole cameras at 90 degrees apart, each 0.5m from the center (facing outwards)  
I've been running the cameras in a unity simulation and it seems no matter what parameters I reconfigure the mercator projection with, the image is never fully showing in rqt (always stretched or cut off at the edges).
I can supply a bagfile with the cam feed if anyone is interested in helping out.  
Thanks in advance.

**Comment by Adidushi** [comment]
https://drive.google.com/file/d/1ouWeQ2I7ZdD4LgH45FcGlYIpF-THuDno/view?usp=sharing
for those interested in the bagfile (~1.2GB)

**Comment by Martin-Oehler** [comment]
Your camera setup should work. Can you please also share your launch/config files so I can take a look?

**Comment by Martin-Oehler** [comment]
I took a look at your bag file. Your camera setup does not follow [ROS conventions](https://www.ros.org/reps/rep-0103.html#axis-orientation). Your camera links have the x-axis pointing fowards. This is fine, but you need a second optical frame with Z axis pointing forwards. The camera info should reference the optical frame with Z-axis fowards in the header. Otherwise, the projection is wrong.

**Comment by Adidushi** [comment]
Thanks - I'll try it out

**Comment by Adidushi** [comment]
Worked great! thanks
