### ISSUE TITLE
How to increase mapping speed

### ISSUE THREAD

**Issue by ifanma** [tu-darmstadt-ros-pkg/image_projection#3]
Hello!

This project is so cool! I tested my insta360 air in realTime, it works well. 
But when changing the pinhole view pose, I find it costs around 4000ms on average to create a mapping. Is that normal? And how to increase the speed? 

Thanks a lot!

**Comment by Martin-Oehler** [comment]
Hello,
thanks for your interest! Changing the projection is quite costly, because each pixel is projected into each camera again. The computation time depends linearly on output resolution and number of cameras. Reducing those should increase your performance.

The computation could also be parallelized very well either on CPU or GPU, but I didn't find time to implement that yet.

If your application is mainly a move-able pinhole projection, you could also use image_projection to create ideal fisheye images, then use [rviz_textured_sphere](https://github.com/UTNuclearRoboticsPublic/rviz_textured_sphere) to render them in a sphere and finally [rviz_camera_stream](https://github.com/lucasw/rviz_camera_stream) do render a pinhole view from the rviz scene.

Best regards,
Martin

**Comment by ifanma** [comment]
Thank you so much for your reply. I will try your method later.
