### ISSUE TITLE
The line beetwen images

### ISSUE THREAD

**Issue by JockTokk** [tu-darmstadt-ros-pkg/image_projection#4]
Hello,

Thanks for the package!
I've got two cameras realsense D455. The result:
![2021-07-26 13-44-10 (2)](https://user-images.githubusercontent.com/61880851/126978685-36515ddc-9312-4ba1-8031-4328935b7f47.gif)

Questions:
1. How to get rid of the line between images to achieve a smooth transition (for example pic.1) from one image to another for different ranges with your package?
2. Which do you know another method to achieve a smooth transition?

Pic.1:
![Снимок экрана от 2021-07-26 16-03-40](https://user-images.githubusercontent.com/61880851/126993234-857e0880-96b0-4ba2-838e-83c1f9a80a9a.png)

For calibration I've used kalibr. 
Сameras are located as follows:
![IMG_20210726_134843](https://user-images.githubusercontent.com/61880851/126978477-d427e5a7-3344-40ac-8c69-4753a5c1b042.jpg)
![IMG_20210726_161604](https://user-images.githubusercontent.com/61880851/126995233-81caa787-41b0-4035-a65a-ff7c24fcd9bb.jpg)

Projections yaml has the following structure:
> $(arg camera_name)_pinhole_front:
>   update_rate: 30
>   always_recompute_mapping: false
>   base_frame: base_link
>   pose: [0, 0, 0, 0, -0.5, 0]
>   virtual_sensor_frame: pinhole_front_camera_frame
>   virtual_sensor_optical_frame: pinhole_front_optical_frame
>   projection_type: image_projection_plugins::PinholeProjection
>   projection_parameters:
>     image_width: 2000
>     image_height: 1500
>     horizontal_fov: 100
>     focal_length: 1

TF-tree:
![frames](https://user-images.githubusercontent.com/61880851/126797738-312bb571-fe2d-4ccc-ad95-cc9cdded8cc0.png)

Thanks for your reply!

**Comment by Martin-Oehler** [comment]
Hey,
thanks for your interest in my project. You have a very interesting setup. May I ask, what your use-case is?

Regarding 1) The visibility of the stitching line depends on two factors. The first factor is the baseline between the cameras. The closer the optical centers, the better. Your cameras are quite far apart, making the stitching artifacts quite noticeable compared to the Insta360 Air with a baseline of 4 mm. 
The second factor is the depth of the projection surface and the real depth at the stitching line. If both distances match, the stitching is perfect. Therefore, you should tune the distance of the projection surface (parameter "focal length", 1 means 1 m in front of your virtual sensor frame) to your standard operational distance. In theory, you always know the real depth because you use an RGB-D camera. You could dynamically adjust the projection surface distance based on these measurements. I also thought about an integration like this, but did not find the time yet.

Regarding 2) Your example likely estimates a homography from common image features and blends the images at the stitching line. My approach does not consider image features but works geometrically alone. Blending would be possible, but is not implemented yet. There are other approaches available, that focus on eliminating the stitching line. You can search Google Scholar for keywords like "image panorama stitching seamless".

If you use the official realsense ros driver, your cameras should publish their own calibration. A second calibration with kalibr should not be necessary. Or do you mean for extrinsic calibration?

Best regards,
Martin

**Comment by JockTokk** [comment]
Thanks for the quick and great answer!

I want to increase my field of view instead of using a fisheye camera. The images will be used to train the neural network.

Yes, I mean for extrinsic calibration and for getting the homography matrix.

Thanks for the ideas!
